// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { handleMockSupabaseRequest } from "./mock-data";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return async (input, init) => {
    const isMock = supabaseKey === "sb_secret_mock_placeholder_key";

    if (!isMock) {
      try {
        const headers = new Headers(
          typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
        );

        if (init?.headers) {
          new Headers(init.headers).forEach((value, key) => headers.set(key, value));
        }

        if (
          isNewSupabaseApiKey(supabaseKey) &&
          headers.get("Authorization") === `Bearer ${supabaseKey}`
        ) {
          headers.delete("Authorization");
        }

        headers.set("apikey", supabaseKey);
        const res = await fetch(input, { ...init, headers });
        if (res.ok) return res;
      } catch (err) {
        console.warn("[Supabase Admin] Network query failed, using fallback mock:", err);
      }
    }

    return handleMockSupabaseRequest(input, init);
  };
}

function createSupabaseAdminClient() {
  const envUrl = process.env["SUPABASE_URL"];
  const envKey = process.env["SUPABASE_SERVICE_ROLE_KEY"];

  const SUPABASE_URL = envUrl || "https://ittfecuwuxosqdbnxffe.supabase.co";
  const SUPABASE_SERVICE_ROLE_KEY = envKey || "sb_secret_mock_placeholder_key";

  if (!envUrl || !envKey) {
    console.warn(
      "[Supabase Admin] Service role credentials missing, using fallback mock admin handler.",
    );
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_SERVICE_ROLE_KEY),
    },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Load inside server handlers: const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
// Top-level import is safe only in other .server.ts modules - route files and *.functions.ts ship to the client bundle.
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
