// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { brokeredPreviewStorage } from "./previewAuthStorage";
import { handleMockSupabaseRequest } from "./mock-data";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return async (input, init) => {
    const isMock = supabaseKey === "sb_publishable_mock_placeholder_key";

    if (!isMock) {
      try {
        const headers = new Headers(
          typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
        );

        if (init?.headers) {
          new Headers(init.headers).forEach((value, key) => headers.set(key, value));
        }

        if (
          isNewSupabaseApiKey(supabaseKey) &&
          headers.get("Authorization") === `Bearer ${supabaseKey}`
        ) {
          headers.delete("Authorization");
        }

        headers.set("apikey", supabaseKey);
        const res = await fetch(input, { ...init, headers });
        if (res.ok) return res;
      } catch (err) {
        console.warn("[Supabase] Network query failed, using fallback mock:", err);
      }
    }

    return handleMockSupabaseRequest(input, init);
  };
}

function createSupabaseClient() {
  const envUrl = import.meta.env["VITE_SUPABASE_URL"] || process.env["SUPABASE_URL"];
  const envKey =
    import.meta.env["VITE_SUPABASE_PUBLISHABLE_KEY"] || process.env["SUPABASE_PUBLISHABLE_KEY"];

  const hasCredentials = Boolean(envUrl && envKey);
  const SUPABASE_URL = envUrl || "https://ittfecuwuxosqdbnxffe.supabase.co";
  const SUPABASE_PUBLISHABLE_KEY = envKey || "sb_publishable_mock_placeholder_key";

  if (!hasCredentials) {
    console.warn(
      "[Supabase] No external Supabase credentials found. Running in AI Studio fallback mode with local mock database.",
    );
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
